const _LIGHT_COLOR = '#797A9E',
      _DARK_COLOR = '#BBBDF6';
const COLOR = {
    BACKGROUND:_LIGHT_COLOR,
    DEBUG:'#FF9900',
    EYE:_LIGHT_COLOR,
    EXTRA:'#72727E',
    EXTRAEXTRA:'#625F63',
    OBJECT:_DARK_COLOR,
    STAR:_DARK_COLOR,
    TEXT:'#9893DA',
};